In [1]:
!ls

cars.csv            model_testing.ipynb


In [5]:
import pandas as pd
from sklearn.linear_model import LinearRegression
import pickle
import numpy as np
import matplotlib.pyplot as plt

In [6]:
df = pd.read_csv('cars.csv')
target = df.mpg
X = df[['cylinders', 'horsepower', 'weight']]

In [7]:
model = LinearRegression()

In [8]:
model.fit(X, target)
print(model.coef_)

[-1.11439132  0.09151962 -0.00850185]


In [9]:
cyl = 8
horse = 200
weight = 2000
model.predict([[cyl, horse, weight]])

array([39.10656063])

In [10]:
pickle.dump(model, open('linreg.p', 'wb'))

In [1]:
#just stopped kernal and restarted to prove something about pickle
model

NameError: name 'model' is not defined

In [2]:
import pickle
model = pickle.load(open('linreg.p', 'rb'))

In [3]:
cyl = 8
horse = 200
weight = 2000
model.predict([[cyl, horse, weight]])

array([39.10656063])